all:
	g++ -g Source.cpp IObject.hpp FieldCage.cpp FieldCage.hpp Field.cpp Field.hpp CreateField.hpp CreateField.cpp FieldView.hpp FieldView.cpp FieldCageView.hpp FieldCageView.cpp -o game -lsfml-graphics -lsfml-window -lsfml-system
