all:
	g++ -g Point.hpp Tile.hpp ITileBuilder.hpp TileBuilder.hpp BuildDirector.hpp Exceptions.hpp CreateGrid.hpp CreateGrid.cpp FieldGrid.hpp FieldGrid.cpp GridView.hpp GridView.cpp main.cpp -o game -lsfml-graphics -lsfml-window -lsfml-system
